/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy_system;

import java.io.IOException;
import static java.util.Collections.list;
import javax.swing.JOptionPane;
import java.awt.List;
import java.io.BufferedWriter;
import java.io.FileWriter;
import static java.util.Collections.list;
/**
 *
 * @author user
 */
public class entering extends javax.swing.JFrame {

    /**
     * Creates new form entering
     */
    public entering() {
        initComponents();
        setSize(1300, 800);
        setLocation(300,200);
        
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        numodmed = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        need = new javax.swing.JRadioButton();
        dontneed = new javax.swing.JRadioButton();
        month = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        backm2 = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Enter  Medicine Info");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 380, 74));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("prescription");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 160, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("number of  medicine");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 260, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("expiry date");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 180, 50));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("price");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 120, 50));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("quantity");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 120, 50));

        numodmed.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(numodmed, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 220, 40));

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField8.setText("jTextField1");
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 220, 40));

        quantity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 220, 40));

        price.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 220, 40));

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField11.setText("jTextField1");
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 220, 40));

        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField12.setText("jTextField1");
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 220, 40));

        need.setBackground(new java.awt.Color(0, 204, 204));
        buttonGroup1.add(need);
        need.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        need.setText("need");
        getContentPane().add(need, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, -1));

        dontneed.setBackground(new java.awt.Color(0, 204, 204));
        buttonGroup1.add(dontneed);
        dontneed.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        dontneed.setSelected(true);
        dontneed.setText("Dont need");
        getContentPane().add(dontneed, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, -1, -1));

        month.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 70, 30));

        year.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });
        getContentPane().add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 80, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel2.setText("month");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 80, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel4.setText("year");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 60, 30));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backm2.setBackground(new java.awt.Color(204, 204, 255));
        backm2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backm2.setText("Back");
        backm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backm2ActionPerformed(evt);
            }
        });
        jPanel1.add(backm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 660, 130, 70));

        save.setBackground(new java.awt.Color(204, 204, 255));
        save.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        save.setText("save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 570, 130, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\medicine.png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 600, 620));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1360, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
      
            
//       medicine med = new  medicine ();
   
        
       
         // LogIn.list.add(med);
          
        try {
            
              medicine med = new  medicine ();

          med.num_of_medicine = Integer.parseInt(this.numodmed.getText() );
          int mnumber =  Integer.parseInt(this.numodmed.getText() );
//          this.numodmed.setText(null);
          //price of med   price
         //price = Double.parseDouble(this.price.getText());
         med.cost=Double.parseDouble(this.price.getText());
//         this.price.setText(null);
         //quantity    q
          med.quantity = Integer.parseInt(this.quantity.getText());
//      this.quantity.setText(null);
        
        //year and month   y/m
      med.expiry_date_year =Integer.parseInt(  this.year.getSelectedItem().toString() );
        med.expiry_date_month =Integer.parseInt(  this.month.getSelectedItem().toString() );
      
      
     
        
       
         //need of prescription    p
        if (need.isSelected()==true)
           
         med.need_prescription=true;
        else med.need_prescription=false;
        
             LogIn.list.add(med);
              JOptionPane.showMessageDialog(null,"medicine  "+mnumber+"  is added");
     
             
//              BufferedWriter br = new  BufferedWriter (new FileWriter  
//                                ("C:\\Users\\user\\Desktop\\design_final\\in.txt")    );
//              
//              br.write("quantity \n"+this.quantity.getText());
//              br.write("price \n"+this.price.getText());              
//              br.close();
//              
              
              
               this.quantity.setText(null);
               this.price.setText(null);
              this.numodmed.setText(null);
             
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(this, "please make sure your informations are right","Erorr", JOptionPane.ERROR_MESSAGE);
       return;
        }

       
       
       
    }//GEN-LAST:event_saveActionPerformed

        
        
        
        
        
        
        
        
        
        
        
    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void backm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backm2ActionPerformed
        // TODO add your handling code here:
      //  this.hide();
      
        try {
             BufferedWriter br = new  BufferedWriter (new FileWriter  
                                ("C:\\Users\\user\\Desktop\\design_final\\in.txt")    );
             for (int i = 0 ; i < LogIn.list.size() ; i++){
       
             
             
              br.write("quantity"+" "+i +" " +LogIn.list.get(i).quantity+" ");
              br.write("price"+ " "+i +" "+LogIn.list.get(i).cost+"\n");             
//              br.close();
              
       } 
               br.close();
        } catch (Exception e) {
        }
      
      
      
      
         this.setVisible(false);
        Manager l = new Manager();
        l.setVisible(true);
        
        
    }//GEN-LAST:event_backm2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(entering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(entering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(entering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(entering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new entering().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backm2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton dontneed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JRadioButton need;
    private javax.swing.JTextField numodmed;
    private javax.swing.JTextField price;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton save;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
