/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy_system;

import java.awt.event.WindowEvent;

/**
 *
 * @author user
 */
public class Manager extends javax.swing.JFrame  {
 
    
    /**
     * Creates new form Manager
     */
    public Manager() {
        initComponents();
        setSize(1300, 800);
        setLocation(300,200);
        
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        viewinventoryfile = new javax.swing.JButton();
        entergoods = new javax.swing.JButton();
        removegoods = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        backl1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Manager");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 236, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewinventoryfile.setBackground(new java.awt.Color(204, 204, 255));
        viewinventoryfile.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        viewinventoryfile.setText("view inventory file");
        viewinventoryfile.setActionCommand("view ");
        viewinventoryfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewinventoryfileActionPerformed(evt);
            }
        });
        jPanel1.add(viewinventoryfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 290, 90));

        entergoods.setBackground(new java.awt.Color(204, 204, 255));
        entergoods.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        entergoods.setText("enter goods");
        entergoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entergoodsActionPerformed(evt);
            }
        });
        jPanel1.add(entergoods, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 290, 90));

        removegoods.setBackground(new java.awt.Color(204, 204, 255));
        removegoods.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        removegoods.setText("remove goods");
        removegoods.setToolTipText("");
        removegoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removegoodsActionPerformed(evt);
            }
        });
        jPanel1.add(removegoods, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 290, 90));

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\medicine.png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 600, 620));

        backl1.setBackground(new java.awt.Color(204, 204, 255));
        backl1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backl1.setText("back");
        backl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backl1ActionPerformed(evt);
            }
        });
        jPanel1.add(backl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 590, 140, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1350, 820));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\medicine.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 600, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewinventoryfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewinventoryfileActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
          view t = new view();
          t.setVisible(true);
    }//GEN-LAST:event_viewinventoryfileActionPerformed

    private void entergoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entergoodsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        entering e = new  entering();
          e.setVisible(true);
        
       
    }//GEN-LAST:event_entergoodsActionPerformed

    private void removegoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removegoodsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
         removing e = new  removing();
          e.setVisible(true);
        
    
    }//GEN-LAST:event_removegoodsActionPerformed

    private void backl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backl1ActionPerformed
        // TODO add your handling code here:
 
        
 
       this.setVisible(false);
        LogIn l = new LogIn();
        l.setVisible(true);
    }//GEN-LAST:event_backl1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backl1;
    private javax.swing.JButton entergoods;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton removegoods;
    private javax.swing.JButton viewinventoryfile;
    // End of variables declaration//GEN-END:variables
}
