/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy_system;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class patientinfo extends javax.swing.JFrame {

    /**
     * Creates new form patientinfo
     */
    public patientinfo() {
        initComponents();
        setSize(1300, 800);
        setLocation(300,200);
        
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pprescription = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        med_number = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        name2 = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        search = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("phone num");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 240, 49));

        pprescription.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pprescription.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(pprescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 250, 49));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("medecine number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 240, 49));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 240, 49));

        phone.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 250, 30));

        med_number.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(med_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 250, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("prescription");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 240, 49));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("patient info");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 240, 49));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 250, 30));

        name2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 250, 30));

        back.setBackground(new java.awt.Color(204, 204, 255));
        back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 680, 140, 70));

        search.setBackground(new java.awt.Color(204, 204, 255));
        search.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        search.setText("search info");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, 200, 70));

        add.setBackground(new java.awt.Color(204, 204, 255));
        add.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        add.setText("add info");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 200, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\medicine.png")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 600, 620));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1360, 810));

        name1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 250, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        
        try {
            
     
         String pname;
         pname = this.name.getText(); 
          for (int i = 0 ; i < LogIn.plist.size() ; i++){
       if (pname.equals(LogIn.plist.get(i).name)) {
    
      this.phone.setText("  " +LogIn.plist.get(i).phone_num);
      this.med_number.setText("  "+LogIn.plist.get(i).number_of_med);
      if (LogIn.plist.get(i).p_prescription){
      this.pprescription.setText(" have prescription " );}
       }
              
          }
         
         
             
             }
        catch(Exception e){
        JOptionPane.showMessageDialog(this, "please make sure your informations are right","Erorr", JOptionPane.ERROR_MESSAGE);
        return;
        }
         
         
    }//GEN-LAST:event_searchActionPerformed
     
             
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
         
            try {
          patient  pl = new  patient();
           
         
      
          pl.p_prescription=true;
          pl.name = name.getText();
          pl.phone_num = Integer.parseInt(this.phone.getText() );
        
          pl.number_of_med = Integer.parseInt(this.med_number.getText() );
        
          LogIn.plist.add(pl);
       
        JOptionPane.showMessageDialog(null," patient   "+name.getText()+"   info  is  added");
           this.phone.setText(null);
           this.name.setText(null);
           this.med_number.setText(null);
        
             }
        catch(Exception e){
        JOptionPane.showMessageDialog(this, "please make sure your informations are right","Erorr", JOptionPane.ERROR_MESSAGE);
       return;
        }
           
    }//GEN-LAST:event_addActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

        this.setVisible(false);
        Pharmacist e = new Pharmacist ();
        e.setVisible(true );

     
    }//GEN-LAST:event_backActionPerformed

            
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patientinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patientinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patientinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patientinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patientinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField med_number;
    private javax.swing.JTextField name;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField name2;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel pprescription;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
