/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy_system;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Pharmacist extends javax.swing.JFrame {
 double fcost=0;
    /**
     * Creates new form Pharmacist
     */
    public Pharmacist() {
        initComponents();
        setSize(1300, 800);
        setLocation(300,200);
        
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Enter = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        show_expiry_date = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        numofmedicine1 = new javax.swing.JTextField();
        show_final_cost = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        show_quentity = new javax.swing.JLabel();
        show_price = new javax.swing.JLabel();
        show_prescription = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Pharmacist interface");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 410, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("number of the medicine");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 28));

        Enter.setBackground(new java.awt.Color(204, 204, 255));
        Enter.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        Enter.setText("Enter");
        Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterActionPerformed(evt);
            }
        });
        getContentPane().add(Enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 100, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("price");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 280, 40));

        show_expiry_date.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        show_expiry_date.setText("e");
        show_expiry_date.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(show_expiry_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 250, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("expiry date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        numofmedicine1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        numofmedicine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numofmedicine1ActionPerformed(evt);
            }
        });
        getContentPane().add(numofmedicine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 250, 40));

        show_final_cost.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        show_final_cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_final_costActionPerformed(evt);
            }
        });
        getContentPane().add(show_final_cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, 260, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("final cost");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 140, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("prescription");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 160, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("quentity");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 120, 40));

        show_quentity.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        show_quentity.setText("q");
        show_quentity.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(show_quentity, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 250, 40));

        show_price.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        show_price.setText("p");
        show_price.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(show_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 250, 40));

        show_prescription.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        show_prescription.setText("pr");
        show_prescription.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(show_prescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 250, 40));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("patient");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 680, 130, 70));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 680, 130, 70));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\medicine.png")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 600, 620));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1350, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterActionPerformed
        // TODO add your handling code here:
    
       try{
              int  mnumber = Integer.parseInt(this.numofmedicine1.getText());
        
       for (int i = 0 ; i < LogIn.list.size() ; i++){
       if (mnumber==LogIn.list.get(i).num_of_medicine ){
       
        this.show_prescription.setText( "  "+LogIn.list.get(i).need_prescription+ " "    );
           this.show_quentity.setText( "    "+LogIn.list.get(i).quantity  );
        this.show_expiry_date.setText( "    "+LogIn.list.get(i).expiry_date_month + "/"+LogIn.list.get(i).expiry_date_year  );
        
         
        this.show_price.setText( "    "+LogIn.list.get(i).cost +"  JD");
         
        fcost +=LogIn.list.get(i).calculate_bill(LogIn.list.get(i).cost  ) ;
         
   this. show_final_cost  .setText( "    "+fcost+"  JD");
       }
       
       }
           
           
       }
        catch(Exception e){
        JOptionPane.showMessageDialog(this, "The Medicine is expiry ","Erorr", JOptionPane.ERROR_MESSAGE);
        return;
        }
       
        
    }//GEN-LAST:event_EnterActionPerformed

    private void numofmedicine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numofmedicine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numofmedicine1ActionPerformed

    private void show_final_costActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_final_costActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_show_final_costActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       // this.hide();
          this.setVisible(false);
          LogIn e = new  LogIn();
          e.setVisible(true);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        patientinfo e = new patientinfo();
        e.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pharmacist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pharmacist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pharmacist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pharmacist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pharmacist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField numofmedicine1;
    private javax.swing.JLabel show_expiry_date;
    private javax.swing.JTextField show_final_cost;
    private javax.swing.JLabel show_prescription;
    private javax.swing.JLabel show_price;
    private javax.swing.JLabel show_quentity;
    // End of variables declaration//GEN-END:variables
}
